message(STATUS "-- Compiling with GNU")
if (USE_MPI)
  message(STATUS "-- Using MPI compiler wrappers...")
  set(CMAKE_C_COMPILER mpicc)
  set(CMAKE_CXX_COMPILER mpicxx)
  set(CMAKE_Fortran_COMPILER mpif90)
else()
  set(CMAKE_C_COMPILER gcc)
  set(CMAKE_CXX_COMPILER g++)
  set(CMAKE_Fortran_COMPILER gfortran)
endif()
set(CMAKE_C_FLAGS "-Wall -Wextra -Wformat=2 -Wsign-conversion -Wold-style-cast")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g3 -Wuninitiazed -Winit-self")
set(CMAKE_C_FLAGS_RELEASE "-O3 -march=native")
set(CMAKE_CXX_FLAGS "-Wall -Wextra -Wformat=2 -Wsign-conversion -Wold-style-cast")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g3 -Wuninitiazed -Winit-self")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -march=native")

