language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true


matrix:
  include:
  - os: linux
#  - os: osx
#    before_install: brew install gcc > /dev/null


install: $TRAVIS_BUILD_DIR/build_METIS.sh
  
script: $TRAVIS_BUILD_DIR/metis-5.1.0/build/Linux-x86_64/programs/graphchk $TRAVIS_BUILD_DIR/tests/tiny_01.graph 

