function(init_gempa)
  if (USE_SFC)
    set(ENABLE_TESTS ON CACHE INTERNAL "")
    set(ENABLE_EXAMPLES ON CACHE INTERNAL "")
    set(BUILD_STATIC_LIBRARIES OFF CACHE INTERNAL "")
    set(CMAKE_BUILD_TYPE Release CACHE INTERNAL "")
  endif()
endfunction()

function(set_gempa)
  if (USE_SFC)
    include_directories(${GEMPA_INCLUDE_DIR})
    target_link_libraries(${PROJECT_NAME} gempa)
  else()
    message("  -- Not using GEMPA...")
    add_definitions(-DNO_SFC)
  endif()
endfunction()